#!/bin/bash

folder="/home/jmro/scripts"
files=$(ls "$folder"/*.sh 2>/dev/null)

if [[ -z "$files" ]]; then
  dialog --msgbox "No se encontraron archivos de script Bash en la carpeta." 8 40
  exit 1
fi

options=()
counter=1

for file in $files; do
  options+=("$counter" "$file")
  ((counter++))
done

selected_option=$(dialog --stdout --menu "Menú de Scripts Bash" 12 60 6 "${options[@]}")

if [[ -n "$selected_option" ]]; then
  option_index=$(echo "$selected_option" | awk -F " " '{print $1}')
  selected_file=$(echo "$files" | sed -n "${option_index}p")

  dialog --title "Confirmación" --yesno "¿Desea ejecutar el archivo '$selected_file' con permisos de superusuario?" 8 60

  if [[ $? -eq 0 ]]; then
    sudo bash "$selected_file"
  else
    bash "$selected_file"
  fi
else
  dialog --msgbox "Opción no válida. Por favor, seleccione un número válido." 8 40
fi
